sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EOCswdnrGMkHdb0LbUCocdx7nJyA5TFSqyluI0/0U1ffO7ja8yHNSa/RLVb48sMYgp/zQ1mfknuKWkx1Zz+zL9uKv8198cM6b/f9Rm0R0WcJtlvWNJCiUShOOz5NWeQoY/muZ6jgnHbZnSZCVzZCFBzTm9UJHeSoQ9cUiGV27yHpVf3lKSJdyQd1m9lqVdN7UcwCDzclPxrc3fDizOSPgj0x0C7jNnUDy+9WqmThjLqdNHHlqZrjxf+nbPOk1Pv5VxzVMiWNmgisUfyStxIYAJdMD/bfttIzDMcd84VHP/zKQ5kjlgMIOsbmwpdGu4j+wXas78qPJFsg3aGyP34Ig8B/y9Umulj2YRviWpgpmovXQfOr/h7H+in9psHDNvtdJ88g4U9eql9C1iOjIbiEtmhupHvGuUV4rz5zp4NrOU+5ukSrrOljMquCM9ov1kYieqLxw9vNaY9CYTiglD/w/KrP1IIywldsAH6/JgOU6DVNmd9EBA3jTaLeslYR+1i4YK6g29JSkoNxfQYBlkGLsH+fyKpo29+DhqE4EpOJQ+TNnJsuINf93OqUTFmBAwGy3mZ0+8PGaBPKxcHCBQj6uHqEGf+VuX9LjeKwV56AitYjWnAQsaE2GXEv3V+PZnKILav0tWFbfj1T9vmz65ia0XCF40dhMzAfW8IZXvWpdOQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Little-Lucy-s-Wonderful-Globe_4538
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy